#!/usr/bin/env bash

# Check if PDF is in folder

CHECK="${1}"
FILETYPE=".pdf"
CMD="fd ${FILETYPE} ${CHECK}"

until eval "${CMD}" | rg ${FILETYPE} > /dev/null
do
  sleep 1
done
echo "File Detected"
eval "${CMD}"
mv "$(eval "$CMD")" "${CHECK}/moved"

########################
### USING RG INSTEAD ###
########################

# CMD="rg --color=never --files "${CHECK}" | rg --color=never "${FILETYPE}""

# until eval "$CMD" > /dev/null
# do
#   sleep 1
# done
# echo "File Detected"
# mv $(eval "$CMD") "${CHECK}/moved"
