#!/usr/bin/env bash

# https://www.cyberciti.biz/faq/grep-regular-expressions/
# https://www.regular-expressions.info/posixbrackets.html       # posix regex
# https://staff.washington.edu/weller/grep.html                 # grep cheatsheet

PDF="$HOME/JupyterNotebook/projects/github/cryptotax/bash/cb_input.pdf"

#### OVERALL FORMAT
# ----------------
PDFCMD="pdftotext -nopgbrk"

OVFORMAT=$(pdftotext -raw -nopgbrk "$PDF" - \
  | sd $(cat replace) '' \
  | sed '/^ *$/d' \
  | sed -e :a -e '/\-$/N; s/\-\n//; ta')

OWNER=$($PDFCMD "$PDF" - \
  | rg -o "Transaction report for \w+ \w+" \
  | sed -e 's/Transaction report for //g')

EMAIL=$($PDFCMD "$PDF" - \
  | rg -o "\S+@\S+$")

RANGE=$($PDFCMD "$PDF" - \
  | rg -o '^(To|From):\s\d{1,4}-\d{1,4}-?\d*T\d{2}:\d{2}:\d{2}Z')

TIMESTAMPS=$(echo "${OVFORMAT}" \
  | rg -o '^\d{1,4}-\d{1,4}-?\d*T\d{2}:\d{2}:\d{2}Z$' \
  | sed -e 's/ /\n/g')

BUYS=$(echo "${OVFORMAT}" \
  | rg --color=never 'Buy' \
  | sed -E 's/Bought.+$//g;s/^[0-9].+Z //g')

BUYS_COUNT=$(echo "${BUYS}" \
  | sed -n '$=')

SELLS=$(echo "${OVFORMAT}" \
  | rg --color=never 'Sell' \
  | sed -E 's/Sold.+$//g')

SELLS_COUNT=$(echo "${OVFORMAT}" \
  | sed -n '$=')

SENTS=$(echo "${OVFORMAT}" \
  | rg --color=never 'Send' \
  | sed -E 's/Sent.+$//g')

SENTS_COUNT=$(echo "${OVFORMAT}" \
  | sed -n '$=')

echo "$SENTS"
# printf "${TIMESTAMPS[0]}\n"
