#!/usr/bin/env bash

# inserts data into sql table - table transactions

DB_USER="root"
DB_PASSWD="freakkkk"
DB_NAME="crypto"
TABLE="transactions"
FILE="data/out/transactions-insert"

cat $FILE | while read \
  user_id \
  doc_id \
  exchange \
  trans_date \
  trans_buy_curr \
  trans_buy_quant \
  trans_buy_cb_USD \
  trans_sell_curr \
  trans_sell_quant \
  trans_sell_cb_USD \
  amount_left \
  ; do
  cat <<-_EOF
  INSERT INTO ${TABLE}(user_id, doc_id, exchange, trans_date, trans_buy_curr, trans_buy_quant, trans_buy_cb_USD, trans_sell_curr, trans_sell_quant, trans_sell_cb_USD, amount_left)
  VALUES ('$user_id', '$doc_id', '$exchange', STR_TO_DATE('$trans_date', '%Y-%m-%dT%H:%i:%sZ'), '$trans_buy_curr', '$trans_buy_quant', '$trans_buy_cb_USD', '$trans_sell_curr', '$trans_sell_quant', '$trans_sell_cb_USD', '$amount_left');
_EOF
  done | mysql -u"${DB_USER}" -p"${DB_PASSWD}" "${DB_NAME}";
