#!/usr/bin/env bash

# inserts data into sql table - table mega

DB_USER="root"
DB_PASSWD="freakkkk"
DB_NAME="crypto"
TABLE="mega"
FILE="data/mega-insert"

cat $FILE | while read -r \
  email \
  pass \
  ; do
  cat <<-_EOF
  INSERT INTO ${TABLE}(email, pass)
  VALUES ('$email', '$pass');
_EOF
  done | mysql -u"${DB_USER}" -p"${DB_PASSWD}" "${DB_NAME}";
