#!/usr/bin/env bash

# inserts data into sql table - table mega

DB_USER="root"
DB_PASSWD="freakkkk"
DB_NAME="crypto"
TABLE="mega"
FILE="data/mega-insert"

cat $FILE | while read \
  doc_id \
  user_id \
  fname \
  exchange \
  ; do
  cat <<-_EOF
  INSERT INTO ${TABLE}(doc_id, user_id, fname, exchange)
  VALUES ($doc_id, '$user_id','$fname', '$exchange');
_EOF
  done | mysql -u"${DB_USER}" -p"${DB_PASSWD}" "${DB_NAME}";
