#!/usr/bin/env bash

# inserts data into sql table - table documents

DB_USER="root"
DB_PASSWD="freakkkk"
DB_NAME="crypto"
TABLE="documents"
FILE="data/out/documents-insert"

cat $FILE | while read \
  user_id \
  exchange \
  filename \
  filesize \
  ; do
  cat <<-_EOF
  INSERT INTO ${TABLE}(user_id, exchange, filename, filesize)
  VALUES ($user_id, '$exchange','$filename', '$filesize');
_EOF
  done | mysql -u"${DB_USER}" -p"${DB_PASSWD}" "${DB_NAME}";
